version: "3"
services:
  proxy:
    build: .

    working_dir: /proxy

    volumes:
      - ./:/proxy/

    ports:
      - 8302:8302
      - 8301:8301
    
    dns:
      - 94.140.14.15
      - 94.140.14.16